sudo: required
services:
  - docker

before_install:
  - docker build -t chadelofson/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chadelofson/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-cls"
  env: "Dockerreactcls-env"
  bucket_name: "elasticbeanstalk-us-west-2-705745555079"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
